name: medhealth
description: "Medhealth application."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.5
  equatable: ^2.0.5
  mailer: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0
  flutter_otp_text_field: ^1.1.0+2
  timer_count_down: ^2.2.1

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  flutter_secure_storage: ^9.2.4
  table_calendar: ^3.1.3
  http_parser: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  intl: ^0.19.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
